name: Build ArKr

on:
  push:
    branches:
      - main
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.h'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.h'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Compile ArKr
      run: g++ ./arkr.cpp -o arkr
    - name: Upload ArKr binary
      uses: actions/upload-artifact@v3
      with:
        name: arkr-binary
        path: ./arkr
